//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SmsSender.rc
//
#define IDD_SMSSENDER_DIALOG            102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_DLGADDRPAD_DIALOG           104
#define IDD_DLGADDRSELECT_DIALOG        105
#define IDR_MAINFRAME                   128
#define IDR_MENU_MAIN                   129
#define IDR_TOOLBAR_MAIN                130
#define IDR_MENU_TRAY_ICON              134
#define IDI_ICON_1                      135
#define IDI_ICON_2                      136
#define IDI_ICON_HU1                    138
#define IDI_ICON_HU2                    139
#define IDI_ICON_SMS                    140
#define IDD_DIALOG_SEND_SMS             141
#define IDD_DIALOG_ABOUT                154
#define NEUSOFT                         157
#define IDR_MENU_SELECT_PATH            160
#define IDD_DIALOG_INPUT_NUMBER         162
#define IDD_DIALOG_CONFIG_PATH          163
#define IDR_SERCH_AVI                   164
#define IDD_DIALOG_SERCH                165
#define IDD_COMSET_DLG                  169
#define IDD_USERSET_DLG                 170
#define IDD_ALARMSET_DLG                171
#define IDD_INTERVALSET_DLG             172
#define IDD_DATASTORAGE_DLG             172
#define IDB_BITMAP1                     176
#define IDD_SPEEDSET_DLG                177
#define IDI_ICON1                       179
#define IDD_CURVECOLOR_DLG              180
#define IDD_DATAQUERY_DLG               181
#define IDI_ICON_GC                     184
#define IDI_ICON_GEAR                   185
#define IDI_ICON2                       186
#define IDI_ICON_RED                    187
#define IDI_ICON_GREEN                  188
#define IDD_PASSWORDSET_DLG             189
#define IDD_INPUTPASSWD_DLG             190
#define IDD_DRAWLINE_DLG                191
#define IDD_SPEEDDOWNSET_DLG            192
#define IDD_DIALOG_FTP_LOGIN            219
#define IDC_LIST_CACHE                  1000
#define IDC_CHECK_AUTO_ATTACH_SERIAL_PORT 1002
#define IDC_CHECK_AUTO_START_SOCKET_LISTEN 1004
#define IDC_EDIT_SERIAL_PORT            1005
#define IDC_EDIT_SOCKET_PORT            1006
#define IDC_LIST_LOG                    1007
#define IDC_BUTTON_RESIZE               1008
#define IDC_BUTTON_RESIZE_V             1009
#define IDC_BUTTON_LOG_DEL_ALL          1010
#define IDC_BUTTON_LOG_DEL              1011
#define IDC_BUTTON_SMS_DEL_ALL          1012
#define IDC_BUTTON_SMS_DEL              1013
#define IDC_EDIT1                       1015
#define IDC_EDIT_FTP_LOGIN_IPADDR       1015
#define IDC_EDIT_COMMENT                1015
#define IDC_EDIT_RUNSPEED               1015
#define IDC_EDIT_OLDPD                  1015
#define IDC_EDIT_PASSWD                 1015
#define IDC_EDIT_SPEEDDOWNRATE          1015
#define IDC_EDIT2                       1016
#define IDC_EDIT_FTP_LOGIN_PORT         1016
#define IDC_EDIT_NEWPD                  1016
#define IDC_EDIT3                       1017
#define IDC_EDIT_FTP_LOGIN_USERNAME     1017
#define IDC_EDIT_CONFIRMPD              1017
#define IDC_STATIC_CENTER               1018
#define IDC_EDIT_FTP_LOGIN_PASSWORD     1018
#define IDC_STATIC_CALLED               1019
#define IDC_EDIT_FTP_LOGIN_FILEPATH     1019
#define IDC_LIST                        1020
#define IDC_BUTTON_ADD                  1021
#define IDC_LIST_FILE                   1021
#define IDC_BUTTON_DEL                  1022
#define IDC_BTN_FTP_LIST                1022
#define IDC_BUTTON_DEL_ALL              1023
#define IDC_EDIT_FTP_LOGIN_BASEPATH     1023
#define IDC_BUTTON_UPDATE               1024
#define IDC_EDIT_FTP_LOGIN_CURRENT_DIR  1024
#define IDC_STATIC_CHAR                 1027
#define IDC_BUTTON_AGAIN                1028
#define IDC_BUTTON_CALLED_ADDR          1029
#define IDC_STATIC_NAME                 1030
#define IDC_BUTTON_APPLY_TIMEOUT        1031
#define IDC_EDIT_TIMEOUT                1032
#define ID_OK                           1033
#define IDC_EDIT_FILEPATH               1034
#define IDC_BUTTON_SAVEPATH             1036
#define IDC_CHECK_AUTOSEND              1037
#define IDC_STATIC_UNIT                 1039
#define IDC_STATIC_CAPTION              1040
#define IDC_EDIT_NUMBER                 1041
#define IDC_BUTTON_CONFIG_PATH          1042
#define IDC_LIST_LOCAL_PATH             1043
#define IDC_LIST_REMOTE_PATH            1044
#define IDC_BUTTON_DEL_PATH             1046
#define IDC_PROGRESS_SEARCH             1047
#define IDC_ANIMATE_SEARCH              1048
#define IDC_BUTTON_AUTO_SEARCH          1049
#define IDC_BUTTON_CANCEL               1050
#define IDC_BN_SEARCH_PORT              1055
#define IDC_CHECK_TEMPERATURE           1056
#define IDC_CHECK_VIBRATION             1060
#define IDC_EDIT_TESTTIME               1062
#define IDC_STATIC_CURVE                1073
#define IDC_EDIT_INTERVAL1              1074
#define IDC_EDIT_INTERVAL2              1075
#define IDC_EDIT_INTERVAL3              1076
#define IDC_EDIT_INTERVAL4              1077
#define IDC_EDIT_INTERVAL5              1078
#define IDC_EDIT_INTERVAL6              1079
#define IDC_EDIT_INTERVAL7              1080
#define IDC_COMBO_NUM                   1081
#define IDC_BUTTON1                     1082
#define IDC_EDIT_STARTBITS              1083
#define IDC_EDIT_STOPBITS               1084
#define IDC_EDIT_DATABITS               1085
#define IDC_EDIT_VERIFYBITS             1086
#define IDC_EDIT_BAUDRATE               1087
#define IDC_CHECK_AUTORELATION          1088
#define IDC_EDIT_USERNAME               1090
#define IDC_EDIT_USERNUM                1091
#define IDC_EDIT_PRODUCTTYPE            1092
#define IDC_EDIT_PRODUCTNUM             1093
#define IDC_EDIT_PRODUCER               1094
#define IDC_EDIT_TESTNAME               1095
#define IDC_EDIT_SPEED1                 1096
#define IDC_EDIT_SPEED2                 1097
#define IDC_EDIT_SPEED3                 1098
#define IDC_EDIT_SPEED4                 1099
#define IDC_EDIT_SPEED5                 1100
#define IDC_EDIT_SPEED6                 1101
#define IDC_EDIT_SPEED7                 1102
#define IDC_EDIT_TEMPERATURE            1103
#define IDC_EDIT_VIBRATION              1104
#define IDC_CHECK_REV                   1105
#define IDC_CHECK_VIBRATION1            1106
#define IDC_CHECK_VIBRATION2            1107
#define IDC_CHECK_VIBRATION3            1108
#define IDC_CHECK_TEMPERATURE1          1109
#define IDC_CHECK_TEMPERATURE2          1110
#define IDC_BN_PRINT                    1110
#define IDC_CHECK_TEMPERATURE3          1111
#define IDC_CHECK_TEMPERATURE4          1112
#define IDC_BN_SELECT                   1112
#define IDC_CHECK_TEMPERATURE5          1113
#define IDC_EDIT_PATH                   1113
#define IDC_CHECK_TEMPERATURE6          1114
#define IDC_EDIT_DIR                    1114
#define IDC_CHECK_TEMPERATURE7          1115
#define IDC_STATIC_DISPLAY              1115
#define IDC_CHECK_TEMPERATURE8          1116
#define IDC_STATIC_PREVIEW              1116
#define IDC_CHECK_TORQUE                1117
#define IDC_STATIC_TITLE                1117
#define IDC_BN_REVCOLOR                 1118
#define IDC_STATIC_OPINION              1118
#define IDC_BN_VIBRATION1               1119
#define IDC_COMBO_VERIFYBITS            1119
#define IDC_BN_VIBRATION2               1120
#define IDC_COMBO_STARTBITS             1120
#define IDC_BN_VIBRATION3               1121
#define IDC_COMBO_BAUDRATE              1121
#define IDC_BN_TEMPERATURE1             1122
#define IDC_COMBO_DATABITS              1122
#define IDC_BN_TEMPERATURE2             1123
#define IDC_COMBO_STOPBITS              1123
#define IDC_BN_TEMPERATURE3             1124
#define IDC_STC_SPLIT                   1124
#define IDC_BN_TEMPERATURE4             1125
#define IDC_STC_LISTBOX                 1125
#define IDC_BN_TEMPERATURE5             1126
#define IDC_STC_DRAWBOX                 1126
#define IDC_BN_TEMPERATURE6             1127
#define IDC_BN_TEMPERATURE7             1128
#define IDC_BN_TEMPERATURE8             1129
#define IDC_BN_TORQUE                   1130
#define IDC_STC_REVCOLOR                1131
#define IDC_STC_VIBRATION1              1132
#define IDC_STC_VIBRATION2              1133
#define IDC_STC_VIBRATION3              1134
#define IDC_STC_TEMPERATURE1            1135
#define IDC_STC_TEMPERATURE2            1136
#define IDC_STC_TEMPERATURE3            1137
#define IDC_STC_TEMPERATURE4            1138
#define IDC_STC_TEMPERATURE5            1139
#define IDC_STC_TEMPERATURE6            1140
#define IDC_STC_TEMPERATURE7            1141
#define IDC_STC_TEMPERATURE8            1142
#define IDC_STC_TORQUE                  1143
#define ID_BUTTON_HIDE                  32771
#define ID_BUTTON_SOCKET_START          32772
#define ID_BUTTON_ATTACH_SERIAL_PORT    32773
#define ID_BUTTON_SHOW                  32774
#define ID_MENU_COMSET                  32775
#define ID_BUTTON_LIST_EXPAND           32776
#define ID_BUTTON_SOCKET_STOP           32777
#define ID_BUTTON_UNCHAIN_SERIAL_PORT   32778
#define ID_MENU_USERSET                 32779
#define ID_APP_SEND_SMS                 32780
#define ID_APP_SMS_ADDRESS              32781
#define ID_BUTTON_START_SENDFILE        32785
#define ID_BUTTON_STOPT_SENDFILE        32786
#define ID_MENU_REMOTE_PATH             32787
#define ID_MENU_LOCAL_PATH              32788
#define ID_MENU_SINGLE_COUNT            32789
#define ID_SEND_INTERVAL                32790
#define ID_SMS_CENTER                   32791
#define ID_MENU_START_RESEND            32793
#define ID_MENU_STOP_RESEND             32794
#define ID_MENU_STOP_IM                 32794
#define ID_MENU_SAVE                    32795
#define ID_MENU_INTERVAL                32796
#define ID_MENU_RELATION_COM            32809
#define ID_MENU_DATA_STORAGE            32812
#define ID_MENU_DATA_QUERY              32813
#define ID_MENU_APPLY_RS485CTRL         32819
#define ID_MENU_RELEASE_RS485CTRL       32820
#define ID_MENU_ROLL_START_IM           32821
#define ID_MENU_REVERSE_START_IM        32822
#define ID_MENU_ALARMSET                32823
#define ID_MENU_SPEEDSET                32824
#define ID_MENU_AUTO_START_IM           32825
#define ID_MENU_CURVE_COLOR             32828
#define ID_MENU_STARTRECORD             32829
#define ID_MENU_STOPRECORD              32830
#define ID_MENU_PASSWDSET               32835
#define ID_MENU_SPEEDDOWNSET            32836
#define IDS_BUTTON_ATTACH_SERIAL_PORT   57666
#define IDS_BUTTON_SOCKET_START         57667
#define IDS_APP_EXIT                    57668
#define IDS_BUTTON_HIDE                 57669
#define IDS_BUTTON_LIST_EXPAND          57670
#define IDS_BUTTON_SOCKET_STOP          57671
#define IDS_APP_SEND_SMS                57672
#define IDS_BUTTON_STARTSENDFILE        57673
#define IDS_BUTTON_STOPSENDFILE         57674
#define IDS_BN_APPLY_RS485CTRL          57675
#define IDS_BN_RELEASE_RS485CTRL        57676
#define IDS_BN_STOP_IM                  57678
#define IDS_BN_RELATION_COM             57682
#define IDS_BN_ROLL_START_IM            57683
#define IDS_BN_REVERSE_START_IM         57684
#define IDS_MENU_AUTO_START_IM          57685
#define IDS_BN_AUTO_START_IM            57685
#define IDS_BN_STARTRECORD              57686
#define IDS_BN_STOPRECORD               57687

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         32837
#define _APS_NEXT_CONTROL_VALUE         1127
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
